/*
 * This file is generated by jOOQ.
 */
package org.cooder.jooq.mate.db.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.cooder.jooq.mate.db.tables.Space;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 不同视图下户型的组成单元，既包含单空间也包含组合空间
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpaceRecord extends UpdatableRecordImpl<SpaceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>space.id</code>. 主键id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>space.id</code>. 主键id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>space.space_code</code>. 空间code
     */
    public void setSpaceCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>space.space_code</code>. 空间code
     */
    public String getSpaceCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>space.space_name</code>. 空间名称
     */
    public void setSpaceName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>space.space_name</code>. 空间名称
     */
    public String getSpaceName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>space.house_layout_code</code>. 户型code
     */
    public void setHouseLayoutCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>space.house_layout_code</code>. 户型code
     */
    public String getHouseLayoutCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>space.space_usage</code>. 单空间：1-客厅，3-餐厅，4-主卧，5-次卧，6-书房，7-厨房，8-卫生间，9-阳台，10-卫生间干区，20-厨房阳台，21-居室阳台，32-次卫，34-1.5卫卫生间，35-客厅阳台; 组合空间：101-主卧及阳台，102-客厅、餐厅及阳台，103-厨房，104-卫生间，105-次卧，106-书房，107-次卫，108-全屋，109-1.5卫卫生间，110-卫生间干区
     */
    public void setSpaceUsage(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>space.space_usage</code>. 单空间：1-客厅，3-餐厅，4-主卧，5-次卧，6-书房，7-厨房，8-卫生间，9-阳台，10-卫生间干区，20-厨房阳台，21-居室阳台，32-次卫，34-1.5卫卫生间，35-客厅阳台; 组合空间：101-主卧及阳台，102-客厅、餐厅及阳台，103-厨房，104-卫生间，105-次卧，106-书房，107-次卫，108-全屋，109-1.5卫卫生间，110-卫生间干区
     */
    public Integer getSpaceUsage() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>space.is_regular</code>. 是否规则空间：0-否，1-是
     */
    public void setIsRegular(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>space.is_regular</code>. 是否规则空间：0-否，1-是
     */
    public Integer getIsRegular() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>space.is_combo</code>. 是否组合空间：0-否，1-是
     */
    public void setIsCombo(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>space.is_combo</code>. 是否组合空间：0-否，1-是
     */
    public Integer getIsCombo() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>space.floor</code>. 楼层
     */
    public void setFloor(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>space.floor</code>. 楼层
     */
    public Integer getFloor() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>space.perimeter_value</code>. 周长
     */
    public void setPerimeterValue(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>space.perimeter_value</code>. 周长
     */
    public BigDecimal getPerimeterValue() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>space.perimeter_unit</code>. 周长单位
     */
    public void setPerimeterUnit(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>space.perimeter_unit</code>. 周长单位
     */
    public String getPerimeterUnit() {
        return (String) get(9);
    }

    /**
     * Setter for <code>space.ground_area_value</code>. 地面面积
     */
    public void setGroundAreaValue(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>space.ground_area_value</code>. 地面面积
     */
    public BigDecimal getGroundAreaValue() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>space.ground_area_unit</code>. 地面面积单位
     */
    public void setGroundAreaUnit(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>space.ground_area_unit</code>. 地面面积单位
     */
    public String getGroundAreaUnit() {
        return (String) get(11);
    }

    /**
     * Setter for <code>space.wall_area_value</code>. 墙面面积
     */
    public void setWallAreaValue(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>space.wall_area_value</code>. 墙面面积
     */
    public BigDecimal getWallAreaValue() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>space.wall_area_unit</code>. 墙面面积单位
     */
    public void setWallAreaUnit(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>space.wall_area_unit</code>. 墙面面积单位
     */
    public String getWallAreaUnit() {
        return (String) get(13);
    }

    /**
     * Setter for <code>space.length_value</code>. 长
     */
    public void setLengthValue(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>space.length_value</code>. 长
     */
    public BigDecimal getLengthValue() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>space.length_unit</code>. 长单位
     */
    public void setLengthUnit(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>space.length_unit</code>. 长单位
     */
    public String getLengthUnit() {
        return (String) get(15);
    }

    /**
     * Setter for <code>space.width_value</code>. 宽
     */
    public void setWidthValue(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>space.width_value</code>. 宽
     */
    public BigDecimal getWidthValue() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>space.width_unit</code>. 宽单位
     */
    public void setWidthUnit(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>space.width_unit</code>. 宽单位
     */
    public String getWidthUnit() {
        return (String) get(17);
    }

    /**
     * Setter for <code>space.height_value</code>. 层高
     */
    public void setHeightValue(BigDecimal value) {
        set(18, value);
    }

    /**
     * Getter for <code>space.height_value</code>. 层高
     */
    public BigDecimal getHeightValue() {
        return (BigDecimal) get(18);
    }

    /**
     * Setter for <code>space.height_unit</code>. 层高单位
     */
    public void setHeightUnit(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>space.height_unit</code>. 层高单位
     */
    public String getHeightUnit() {
        return (String) get(19);
    }

    /**
     * Setter for <code>space.window_linear_meters_value</code>. 窗户延米
     */
    public void setWindowLinearMetersValue(BigDecimal value) {
        set(20, value);
    }

    /**
     * Getter for <code>space.window_linear_meters_value</code>. 窗户延米
     */
    public BigDecimal getWindowLinearMetersValue() {
        return (BigDecimal) get(20);
    }

    /**
     * Setter for <code>space.window_linear_meters_unit</code>. 窗户延米单位
     */
    public void setWindowLinearMetersUnit(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>space.window_linear_meters_unit</code>. 窗户延米单位
     */
    public String getWindowLinearMetersUnit() {
        return (String) get(21);
    }

    /**
     * Setter for <code>space.order</code>. 空间的显示顺序
     */
    public void setOrder(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>space.order</code>. 空间的显示顺序
     */
    public Integer getOrder() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>space.parent_code</code>. 空间具有组合关系时，存储父空间code
     */
    public void setParentCode(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>space.parent_code</code>. 空间具有组合关系时，存储父空间code
     */
    public String getParentCode() {
        return (String) get(23);
    }

    /**
     * Setter for <code>space.cu_name</code>. 创建人
     */
    public void setCuName(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>space.cu_name</code>. 创建人
     */
    public String getCuName() {
        return (String) get(24);
    }

    /**
     * Setter for <code>space.cuid</code>. 创建人ucid
     */
    public void setCuid(Long value) {
        set(25, value);
    }

    /**
     * Getter for <code>space.cuid</code>. 创建人ucid
     */
    public Long getCuid() {
        return (Long) get(25);
    }

    /**
     * Setter for <code>space.mu_name</code>. 更新人
     */
    public void setMuName(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>space.mu_name</code>. 更新人
     */
    public String getMuName() {
        return (String) get(26);
    }

    /**
     * Setter for <code>space.muid</code>. 更新人ucid
     */
    public void setMuid(Long value) {
        set(27, value);
    }

    /**
     * Getter for <code>space.muid</code>. 更新人ucid
     */
    public Long getMuid() {
        return (Long) get(27);
    }

    /**
     * Setter for <code>space.ctime</code>. 创建时间 
     */
    public void setCtime(LocalDateTime value) {
        set(28, value);
    }

    /**
     * Getter for <code>space.ctime</code>. 创建时间 
     */
    public LocalDateTime getCtime() {
        return (LocalDateTime) get(28);
    }

    /**
     * Setter for <code>space.mtime</code>. 更新时间
     */
    public void setMtime(LocalDateTime value) {
        set(29, value);
    }

    /**
     * Getter for <code>space.mtime</code>. 更新时间
     */
    public LocalDateTime getMtime() {
        return (LocalDateTime) get(29);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpaceRecord
     */
    public SpaceRecord() {
        super(Space.SPACE);
    }

    /**
     * Create a detached, initialised SpaceRecord
     */
    public SpaceRecord(Long id, String spaceCode, String spaceName, String houseLayoutCode, Integer spaceUsage, Integer isRegular, Integer isCombo, Integer floor, BigDecimal perimeterValue, String perimeterUnit, BigDecimal groundAreaValue, String groundAreaUnit, BigDecimal wallAreaValue, String wallAreaUnit, BigDecimal lengthValue, String lengthUnit, BigDecimal widthValue, String widthUnit, BigDecimal heightValue, String heightUnit, BigDecimal windowLinearMetersValue, String windowLinearMetersUnit, Integer order, String parentCode, String cuName, Long cuid, String muName, Long muid, LocalDateTime ctime, LocalDateTime mtime) {
        super(Space.SPACE);

        setId(id);
        setSpaceCode(spaceCode);
        setSpaceName(spaceName);
        setHouseLayoutCode(houseLayoutCode);
        setSpaceUsage(spaceUsage);
        setIsRegular(isRegular);
        setIsCombo(isCombo);
        setFloor(floor);
        setPerimeterValue(perimeterValue);
        setPerimeterUnit(perimeterUnit);
        setGroundAreaValue(groundAreaValue);
        setGroundAreaUnit(groundAreaUnit);
        setWallAreaValue(wallAreaValue);
        setWallAreaUnit(wallAreaUnit);
        setLengthValue(lengthValue);
        setLengthUnit(lengthUnit);
        setWidthValue(widthValue);
        setWidthUnit(widthUnit);
        setHeightValue(heightValue);
        setHeightUnit(heightUnit);
        setWindowLinearMetersValue(windowLinearMetersValue);
        setWindowLinearMetersUnit(windowLinearMetersUnit);
        setOrder(order);
        setParentCode(parentCode);
        setCuName(cuName);
        setCuid(cuid);
        setMuName(muName);
        setMuid(muid);
        setCtime(ctime);
        setMtime(mtime);
    }
}
