/*
 * This file is generated by jOOQ.
 */
package org.cooder.jooq.mate.db;


import org.cooder.jooq.mate.db.tables.HouseLayout;
import org.cooder.jooq.mate.db.tables.Space;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 户型就是房子的结构与形状，一般与设计方案相关，不同的设计会产出不同的户型，只要数据有调整，就会新生成一个户型
     */
    public static final HouseLayout HOUSE_LAYOUT = HouseLayout.HOUSE_LAYOUT;

    /**
     * 不同视图下户型的组成单元，既包含单空间也包含组合空间
     */
    public static final Space SPACE = Space.SPACE;
}
